apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkify.fullname" . }}
  labels:
    {{- include "linkify.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "linkify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "linkify.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "linkify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "LITESTREAM_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  key:  litestream_access_key_id
                  name: {{ .Release.Name }}-s3-auth
            - name: "LITESTREAM_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  key:  litestream_secret_access_key
                  name: {{ .Release.Name }}-s3-auth
            - name: "DB_NAME"
              value: {{ .Values.litestream.db_name }}
            - name: "REPLICA_URL"
              value: {{ .Values.litestream.replica_bucket_url }}/{{ .Values.litestream.db_name }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /version
              port: 8001
          readinessProbe:
            httpGet:
              path: /version
              port: 8001
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
