apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-auth
data:
  litestream_access_key_id: {{ .Values.litestream.access_key_id | b64enc }}
  litestream_secret_access_key: {{ .Values.litestream.secret_access_key | b64enc }}
